leave the temporary directories behind
This helps with debugging failures.
Also the directory deletion implementation is broken on Windows anyway and
sometimes fails with errors like:

```
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\tmpc8za73y6\\private\\privatestorageio-zkapauthz-v1.sqlite3'
```